### ISSUE TITLE
Traducir Primer Modulo: Using the tour

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/go-tour-es#1]
### Modificación 
Se crea este issue para comenzar con la traducción del Go Tour.
Se deben de modificar las 3 paginas del inicio. Las mismas se encuentras en las siguientes rutas:
Tour > content > welcome > hello.go
Tour > content > welcome.article

## Issues 
Para seguir el hilo de este issue, cada vez que se cree uno se deberán seguir los siguientes pasos: 
 - El nombre del issue sera: Traducir {Nro del modulo} Modulo: {Nombre del modulo}. Ejemplo: Traducir Segundo Modulo: Basics.
 - Si deseamos comenzar la traducción de un modulo, debemos de asignarnos el issue para saber quien lo esta realizando. Se puede hacer de la siguiente manera: 

![image](https://github.com/gophers-latam/go-tour-es/assets/73196303/c9ddef2b-278d-4233-ad02-3874f6f5910f)

- Si comenzamos la traducción y no tenemos tiempo para finalizarla o son muchas paginas por traducir, lo recomendable seria comentar el issue en cuestión con la situación que este pasando, y realizar el PR solicitado con lo que se tenga hasta el momento. Para que alguien mas puede tomar la traducción y avanzar para finalizar el modulo. Tambien podemos avisar en el canal **_#translations_** de la comunidad (Gophers Latam).

**Comment by ThiagoMowszet** [comment]
Me asigno este issue para comenzar con la traducción del primer modulo.

**Comment by zeroidentidad** [comment]
> Me asigno este issue para comenzar con la traducción del primer modulo.

para seguir con el ejemplo 👍🏽
