### ISSUE TITLE
Corregir nombres, typos y textos

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/go-tour-es#23]
Hola! en este issue quiero seguir puliendo el tour, para ello, solicito los siguientes cambios:

1. Cambiar el nombre de la comunidad por `Gophers LATAM`.

![image](https://github.com/user-attachments/assets/be481d4d-c917-4a98-998c-51fbde505707)

2. Modificar el texto a `El servicio recibe un programa Go, compila, vincula y ejecuta el programa dentro de una zona de pruebas, luego devuelve la salida.`

![image](https://github.com/user-attachments/assets/728a97ba-ac5a-44d7-9e7e-1925b876d2ce)

3. Cambiar el texto del punto 2 al siguiente: `En el playground, el tiempo empieza el 2009-11-10 23:00:00 UTC (determinar el significado de esta fecha es un ejercicio para el lector). Esto facilita el almacenamiento en caché de los programas al proporcionarles una salida determinista.` 

4. Verificar si esta función sigue ocurriendo, en mi caso, la funcion siempre retorna un numero diferente (entiendo que esto ocurre porque hicieron modificaciones en el playground).

![image](https://github.com/user-attachments/assets/3b3ff583-3940-4aff-8141-384556422a72)

5. Agregar `Spanish - Español` entre Polonia y Thai, asi queda en orden alfabetico (Ingles)

![image](https://github.com/user-attachments/assets/d2a759bc-b516-4e9b-9598-4d936593bfdd)

**Comment by NikolaM-Dev** [comment]
@ThiagoMowszet, Now we can close this issue, right?
