### ISSUE TITLE
Traducir Segundo Modulo: Basics

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/go-tour-es#3]
### Basics
Se deberá traducir el segundo modulo del Go Tour.
El mismo cuenta con 17 paginas y archivos *.go a traducir. Los mismos se encuentran en:
**_Tour > content >  basics > *.go
Tour > content > basics.article_**

![image](https://github.com/gophers-latam/go-tour-es/assets/73196303/05c44f76-361b-4140-836b-136bf2250699)

![image](https://github.com/gophers-latam/go-tour-es/assets/73196303/8a6c4f53-99c2-4ad8-862c-b98667204db4)

**Comment by zeroidentidad** [comment]
**Nota**: el contenido con etiqueta de comentario por ejemplo _**#appengine**_ no se renderizan en la pagina. No es necesario traducirlo. Igual considerar si removerlos 🤔

**Comment by ThiagoMowszet** [comment]
Si es cierto que no se ejecutan. 
Pero es debido a que estamos traduciendo la versión offline. Entiendo que cuando presentemos está traducción a Go, se podrá usar estás traducciónes comentadas.
