### ISSUE TITLE
Traducir Cuarto Modulo: More types: structs, slices, and maps.

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/go-tour-es#6]
Se deberá de traducir el cuarto modulo del tour de Go.
El mismo cuenta con 27 paginas y varios *.go a editar. Los mismos se encuentran en la siguiente ruta:

**_tour > content > moretypes > *.go
tour > content > moretypes.article_**

Dejo una imagen de estas rutas para una mejor visualización:

![image](https://github.com/gophers-latam/go-tour-es/assets/73196303/a232fd0c-c63b-40a5-a499-ff9e2fe7988c)

**Comment by jirigoin** [comment]
Buenas, tomo este issue si les parece bien

**Comment by ThiagoMowszet** [comment]
Excelente @jirigoin!
