### ISSUE TITLE
Traducir Sexto y ultimo Modulo: Concurrencia

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/go-tour-es#8]
Se deberá de traducir el ultimo modulo del tour de Go.
El mismo cuenta con 11 paginas y varios *.go a traducir, las cuales se encuentran en las siguientes rutas:

**_tour > content > concurrency > *.go
tour > content > concurrency.article_**

Dejo imagen de las rutas, para una mejor visualización: 

![image](https://github.com/gophers-latam/go-tour-es/assets/73196303/bcb5ee05-97c5-46c5-8d3e-999dc54544a0)

**Comment by profe-ajedrez** [comment]
@ThiagoMowszet  @zeroidentidad 

He decidido usar la siguiente nomenclatura:

* goroutines -> gorutinas
* buffered channels -> canales con buffer
* as part of the core language -> como parte del core del lenguaje

Escucho sugerencias mientras avanzo en la localización

**Comment by ThiagoMowszet** [comment]
Hola @profe-ajedrez!
Muchas gracias por las aclaraciones.
Me gustan tus propuestas, por mi sigamos avanzando! :1st_place_medal:

**Comment by zeroidentidad** [comment]
👍🏽 excelente
